### ISSUE TITLE
vite 创建的Vue3项目不能引入 vue-pdf，报错process is not defined     at vuePdfNoSss

### ISSUE THREAD

**Issue by zengqinhll** [FranckFreiburger/vue-pdf#379]
process is not defined     at vuePdfNoSss

**Comment by FrancoMSarabia** [comment]
I have the same error in vue 3

**Comment by SagarVishal** [comment]
I have the same error as well

**Comment by yaelahan** [comment]
꧋ꦱꦪꦩꦼꦤ꧀ꦝꦥꦠ꧀ꦏꦤ꧀ꦩꦱꦭꦃꦪꦁꦱꦩꦏꦼꦠꦶꦏꦩꦼꦁꦒꦸꦤꦏꦤ꧀ꦮ꦳ꦶꦠꦺ

**Comment by yil3** [comment]
vue2也一样，应该是这个库使用了require？

**Comment by silverlovesl** [comment]
> I have the same error as well
`process.env` is removed from vite by commit [8ad7ec](https://github.com/vitejs/vite/commit/8ad7ecd1029bdc0b47e55877db10ac630829c7e5)

you can add 
```
define: {
    'process.env': {}, // 絶対削除しないでください。
  },
```
into your vite.config.ts

BTW , this library seems not working for vite so far.

**Comment by ZzzilH** [comment]
I have the same error in vue 3

**Comment by toplyb** [comment]
I had the same problem in `vite 3.2`, at the same time, I get `require is not a function`. When will it be resolved?

**Comment by chenweigh** [comment]
vite3+vue3
问题1： require 不能用，install vite-plugin-require-transform
问题2:  [plugin:vite:import-analysis] Failed to resolve import "worker-loader!pdfjs-dist/es5/build/pdf.worker.js" from "node_modules/vue-pdf/src/vuePdfNoSss.vue". Does the file exist?
问题1 fix后，又遇到问题2，推测是安装了1的问题。
崩溃中。。。
vite 怎么办

**Comment by chenweigh** [comment]
> https://www.npmjs.com/package/dy-vite-vue-pdf

`dy-vite-vue-pdf` 也有问题
SyntaxError: The requested module '/node_modules/dy-vite-vue-pdf/src/pdf.worker.min.js?v=f9c00aee' does not provide an export named 'default' (at viteVuePdf.vue:7:8)

**Comment by AnndyBrick** [comment]
> > https://www.npmjs.com/package/dy-vite-vue-pdf
> 
> `dy-vite-vue-pdf` 也有问题 SyntaxError: The requested module '/node_modules/dy-vite-vue-pdf/src/pdf.worker.min.js?v=f9c00aee' does not provide an export named 'default' (at viteVuePdf.vue:7:8)

想问下最后有找到解决方法吗？

**Comment by frallisland** [comment]
i have some erro in vue3 project, seem the repo not support vue3+vite😢

**Comment by a21ns1g4ts** [comment]
dont try install with vite

**Comment by mariree** [comment]
same problem in vite 5.4.0, at the same time, I get require is not a function
