### ISSUE TITLE
pdf预览显示不出来，控制太提示TypeError: Cannot read properties of null (reading 'sendWithPromise')

### ISSUE THREAD

**Issue by cv-yee** [FranckFreiburger/vue-pdf#432]
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'sendWithPromise')
    at WorkerTransport.getAnnotations (pdf.js:14349:34)
    at PDFPageProxy.getAnnotations (pdf.js:12864:51)
    at PDFJSWrapper.eval (pdfjsWrapper.js:237:13)
<img width="811" alt="企业微信截图_4b24d10a-fe49-49c8-9dd1-e3b16f777add" src="https://github.com/user-attachments/assets/f7e57e43-8b85-4ffd-adf8-125245a32f97">

**Comment by jiangxinyu50** [comment]
只能改源码了
