### ISSUE TITLE
Dynamic import in pdf.vue

### ISSUE THREAD

**Issue by andreasvirkus** [FranckFreiburger/vue-pdf#55]
When building a Webpack bundle, then `babel-loader` complains about vue-pdf dist file's dynamic import() token:
```
build	02-Feb-2018 13:33:20	ERROR in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./node_modules/vue-pdf/src/pdf.vue
build	02-Feb-2018 13:33:20	Module build failed: SyntaxError: Unexpected token (186:10)
build	02-Feb-2018 13:33:20	
build	02-Feb-2018 13:33:20	  184 | 		this.fetch = function(query) {
build	02-Feb-2018 13:33:20	  185 | 
build	02-Feb-2018 13:33:20	> 186 | 			return import('raw-loader!pdfjs-dist/cmaps/'+query.name+'.bcmap' /* webpackChunkName: "noprefetch-[request]" */)
build	02-Feb-2018 13:33:20	      | 			       ^
build	02-Feb-2018 13:33:20	  187 | 			.then(function(bcmap) {
build	02-Feb-2018 13:33:20	  188 | 
build	02-Feb-2018 13:33:20	  189 | 				return {
build	02-Feb-2018 13:33:20	
build	02-Feb-2018 13:33:20	 @ ./node_modules/vue-pdf/src/pdf.vue 7:2-87
```

**Comment by FranckFreiburger** [comment]
`import()` syntax require `babel-plugin-syntax-dynamic-import` plugin.
I will try to replace it with `require.ensure()`

**Comment by FranckFreiburger** [comment]
please try v3.1.8+

**Comment by andreasvirkus** [comment]
```
ERROR in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.j
s?type=script&index=0!./node_modules/vue-pdf/src/pdf.vue
Module build failed: ReferenceError: Unknown plugin "@babel/plugin-syntax-dynamic
-import" specified in "/Users/andreas.virkus/code/sweden-loan-application/node_modules/vue-pdf/.babelrc" at 0, attempted to resolve relative to "/Users/andreas.virkus/code/sweden-loan-application/node_modules/vue-pdf"
    at /Users/andreas.virkus/code/sweden-loan-application/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/Users/andreas.virkus/code/sweden-loan-application/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/andreas.virkus/code/sweden-loan-application/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/andreas.virkus/code/sweden-loan-application/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/andreas.virkus/code/sweden-loan-application/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/andreas.virkus/code/sweden-loan-application/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/andreas.virkus/code/sweden-loan-application/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/andreas.virkus/code/sweden-loan-application/node_modules/babel-loader/lib/index.js:46:20)
    at Object.module.exports (/Users/andreas.virkus/code/sweden-loan-application/node_modules/babel-loader/lib/index.js:163:20)
 @ ./node_modules/vue-pdf/src/pdf.vue 7:2-87
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./client/src/steps/Signing.vue
 @ ./client/src/steps/Signing.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./client/src/App.vue
 @ ./client/src/App.vue
```

**Comment by FranckFreiburger** [comment]
@babel/plugin-syntax-dynamic-import is for babel 7(beta), use previous one instead

**Comment by andreasvirkus** [comment]
Yep, issue seems to be resolved in the newer versions, thanks! 🎉
